server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.wyy22.wyy.entity

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/wangyi?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 2
  thymeleaf:
    cache: false # 关闭页面缓存
    encoding: UTF-8 # 模板编码
    prefix: classpath:/templates/  # 页面映射路径
#    suffix: .ftl # 试图后的后缀
    suffix: .html # 试图后的后缀


